name: KBO-Bot
on:
  schedule:
    - cron: '0 21 * * *' # 한국 시간 매일 새벽 6시 실행
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4 # 👈 'setup-python' 이어야 합니다!
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Crawler
        env:
          KBO_INGEST_URL: ${{ secrets.KBO_INGEST_URL }}
          KBO_INGEST_TOKEN: ${{ secrets.KBO_INGEST_TOKEN }}
        run: python crawling.py
